# Generated by Django 4.0.4 on 2022-06-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tag_ismain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='productPictures/', verbose_name='Image'),
        ),
    ]
