# Generated by Django 4.0.4 on 2022-06-14 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
