# Generated by Django 4.0.4 on 2022-06-19 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_image_product_alter_tag_product'),
        ('customers', '0002_alter_customer_options_alter_customer_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewhistory',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewHistory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viewhistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='viewHistory', to='products.product'),
        ),
    ]
