# Generated by Django 4.0.4 on 2022-06-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_viewhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='picture',
            field=models.ImageField(null=True, upload_to='profilePictures/', verbose_name='Profile Picture'),
        ),
    ]
