# Generated by Django 4.0.4 on 2022-06-19 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_viewhistory_customer_alter_viewhistory_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewhistory',
            name='viewedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Viewed At'),
            preserve_default=False,
        ),
    ]
