# Generated by Django 4.0.4 on 2022-06-28 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_tags_alter_tag_category'),
        ('customers', '0004_viewhistory_viewedat'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='viewhistory',
            unique_together={('customer', 'product')},
        ),
    ]
