# Generated by Django 4.0.4 on 2022-06-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_viewhistory_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='deliveredAt',
        ),
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.CharField(blank=True, max_length=100, verbose_name='Status'),
        ),
    ]
