# Generated by Django 4.0.4 on 2022-06-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_remove_delivery_deliveredat_delivery_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivered',
        ),
        migrations.AddField(
            model_name='delivery',
            name='willDeliveredAt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='will be delivered at'),
        ),
    ]
