# Generated by Django 4.0.4 on 2022-06-30 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_remove_delivery_delivered_delivery_willdeliveredat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='willDeliveredAt',
            new_name='arrivalDate',
        ),
    ]
