# Generated by Django 4.0.4 on 2022-07-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_rename_willdeliveredat_delivery_arrivaldate'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Delivery Address'),
        ),
    ]
