# Generated by Django 4.0.4 on 2022-07-06 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_location'),
        ('customers', '0010_alter_delivery_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='deliveries', to='products.product'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(blank=True, choices=[('ding', 'delivering'), ('ded', 'delivered'), ('cel', 'cancelled')], max_length=100, verbose_name='Status'),
        ),
    ]
