# Generated by Django 4.0.4 on 2022-07-07 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_alter_delivery_product_alter_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(blank=True, choices=[('DELIVERING', 'delivering'), ('DELIVERED', 'delivered'), ('CANCELLED', 'cancelled')], max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='favourite',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL),
        ),
    ]
