# Generated by Django 4.0.4 on 2022-07-08 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_cartproduct_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproduct',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
