# Generated by Django 4.0.4 on 2022-07-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_location'),
        ('customers', '0015_remove_cartproduct_quantity_cartproduct_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='quantity',
        ),
        migrations.AddField(
            model_name='delivery',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Amount'),
        ),
        migrations.AlterUniqueTogether(
            name='cartproduct',
            unique_together={('customer', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together={('customer', 'product')},
        ),
    ]
