# Generated by Django 4.0.4 on 2022-07-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0017_remove_cartproduct_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='amount'),
        ),
    ]
