# Generated by Django 4.0.4 on 2022-07-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0019_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='firstName',
            field=models.CharField(blank=True, max_length=15, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lastName',
            field=models.CharField(blank=True, max_length=30, verbose_name='Last name'),
        ),
    ]
