# Generated by Django 4.0.4 on 2022-05-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(max_length=200)),
                ('brand', models.CharField(max_length=50, verbose_name='Brand')),
                ('thumbnail', models.ImageField(upload_to='images/', verbose_name='Thumbnail')),
                ('author', models.CharField(max_length=60, verbose_name='Author')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('discount', models.IntegerField(default=0, null=True, verbose_name='Discount')),
                ('discountPrice', models.PositiveIntegerField(null=True, verbose_name='Price with Discount')),
                ('color', models.CharField(max_length=50, verbose_name='Color')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
    ]
