# Generated by Django 4.0.4 on 2022-06-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discountPrice',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Price with Discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(upload_to='productPictures/', verbose_name='Thumbnail'),
        ),
    ]
