# Generated by Django 4.0.4 on 2022-06-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
    ]
